
import Footer from "@/components/Footer";
import "./globals.css";
import Topo from "@/components/Topo";

export const metadata = { 
  title: "Home | Vivant",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Topo/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
