
import Topo from "@/components/Topo";
import "./globals.css";
import Footer from "@/components/Footer";

export const metadata = { 
  title: "Home | Vivant",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon-16x16.png"
  }
  
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Topo/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
